#!/bin/sh
set -eu

export PULUMI_HOME=/workspace/.pulumi
export PULUMI_BACKEND_URL=file:///workspace/.pulumi
export PULUMI_CONFIG_PASSPHRASE=localstack
export PULUMI_SKIP_UPDATE_CHECK=true
export PULUMI_DISABLE_CHECKPOINTS=true

exec /workspace/.pulumi-cli/pulumi "$@"
